#!/bin/bash
#
#  $Header$
#  $Name$
#


FC=mpif77
CC=mpicc
DEFINES='-D_BYTESWAPIO -DWORDLENGTH=4'
CPP='cpp  -traditional -P'
NOOPTFLAGS='-O0'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS='-Wimplicit -Wunused -Wuninitialized'
    FOPTIM='-O3 -malign-double -funroll-loops'
else
    #  Try to follow IEEE-754
    FFLAGS='-Wimplicit -Wunused -ffloat-store'
    FOPTIM='-O0 -malign-double'
fi

INCLUDES='-I/usr/local/mpich/mpich-gcc/include'
#LIBS='-L/usr/local/mpich/mpich-gcc/lib'

