# Travis file for running some basic set of testreport checks on each commit
#
#
services: 
 - docker
 
before_install:
 - docker pull mitgcm/testreport-images:fc11-base-20170715
 - docker run  -v `pwd`:/MITgcm --name fc11-testreport -t -d mitgcm/testreport-images:fc11-base-20170715 /bin/bash
 - docker exec -i fc11-testreport rpm -vv --rebuilddb
 - docker exec -i fc11-testreport df -h
 - docker exec -i fc11-testreport ls -altr /MITgcm
 - docker exec -i fc11-testreport yum install python-pip
 - docker exec -i fc11-testreport yum install gcc-gfortran
 - docker pull mitgcm/testreport-images:centos-7.3.1611-20170809-v5
 - docker run  -v `pwd`:/MITgcm -h c7-n001 --name c7-n001 -d -t mitgcm/testreport-images:centos-7.3.1611-20170809-v5 /bin/bash
 - docker run  -v `pwd`:/MITgcm -h c7-n002 --name c7-n002 -d -t mitgcm/testreport-images:centos-7.3.1611-20170809-v5 /bin/bash
 - docker exec -t -i c7-n001 /usr/sbin/sshd
 - docker exec -t -i c7-n002 /usr/sbin/sshd
 - /bin/bash ./ci/travis/functions/set_container_hosts.sh c7-n001 c7-n002


script: 
 - echo `pwd`
 - docker exec -i c7-n001 /bin/bash /MITgcm/ci/travis/functions/simple_mpi_travis_docker_check.sh
 - source /MITgcm/ci/travis/functions/simple_sourced_file_test.sh 
 - docker exec -i fc11-testreport bash -c "cd /MITgcm/verification; ./testreport -t tutorial_barotropic_gyre"
 - docker exec -i c7-n001 bash -c "cd /MITgcm/verification; ./testreport -t tutorial_barotropic_gyre"
