#!/bin/bash
#
#  $Header$
#

DEFINES='-D_BYTESWAPIO -DWORDLENGTH=4'
CPP='/lib/cpp -traditional -P'
FC='lf95'
# FFLAGS='-byteswapio -r8 -Mnodclchk -Mextend'
# FOPTIM='-tp p6 -v -O2 -Munroll -Mvect=cachesize:512000,transform -Kieee'

