#!/bin/bash
#
#  $Header$
#


FC='/opt/mpich/bin/mpif77'
CC='gcc'
LINK='/opt/mpich/bin/mpif77'
DEFINES='-DWORDLENGTH=4'
CPP='cpp  -traditional -P'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS='-byteswapio -r8 -Mnodclchk -Mextend'
    FOPTIM='-tp p6 -v -O2 -Munroll -Mvect=cachesize:512000,transform'
else
    #  Try to follow IEEE-754
    FFLAGS='-byteswapio -r8 -Mnodclchk -Mextend'
    FOPTIM='-tp p6 -v -O2 -Munroll -Mvect=cachesize:512000,transform -Kieee'
fi

INCLUDES='-I/opt/mpich/include'
LIBS='-L/opt/mpich/lib/ -lfmpich -lmpich'
