#!/bin/bash
#
#  $Header$
#

DEFINES='-DWORDLENGTH=4'
CPP='/lib/cpp -traditional -P'
FC='pgf77'
CC='gcc'
FFLAGS='-byteswapio -r8 -Mnodclchk -Mextend'
FOPTIM='-tp p6 -v -O2 -Munroll -Mvect=cachesize:512000,transform -Kieee'

