#!/bin/bash
#
#  $Header$
#

FC='pgf77'
CC='gcc'
DEFINES='-DWORDLENGTH=4'
CPP='cpp -traditional -P'

if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS='-byteswapio -r8 -Mnodclchk -Mextend'
    FOPTIM='-tp p6 -v -O2 -Munroll'
# -Mvect=cachesize:512000,transform
else
    #  Try to follow IEEE-754
    FFLAGS='-byteswapio -r8 -Mnodclchk -Mextend'
    FOPTIM='-tp p6 -v -O2 -Munroll -Kieee'
# -Mvect=cachesize:512000,transform
fi

