#!/bin/bash
#
#  $Header$
#

DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -D_BYTESWAPIO -DWORDLENGTH=4'

CPP='/lib/cpp  -traditional -P'
FFLAGS='-Wimplicit -Wunused -Wuninitialized -ffloat-store'
FOPTIM='-O3 -malign-double -funroll-loops'
NOOPTFLAGS='-O0'
FC='/usr/local/pkg/mpi/mpi-1.2.4..8a-gm-1.5/g77/bin/mpif77'
INCLUDEDIRS='/usr/local/pkg/mpi/mpi-1.2.4..8a-gm-1.5/g77/include'

