#!/bin/bash
#
#  $Header$
#  $Name$
#


FC=ifc
CC=gcc
DEFINES='-D_BYTESWAPIO -DWORDLENGTH=4'
CPP='cpp  -traditional -P'
FOPTIM='-O3 -align'

#  Note that the -mp switch is for ieee "maintain precision" and is
#  roughly equivalent to -ieee
if test "x$IEEE" = x ; then
    FFLAGS='-132 -r8 -i4 -w95 -W0 -WB'
#P3 FOPTIM=$FOPTIM' -tpp6 -xWKM'
#P4 FOPTIM=$FOPTIM' -tpp7 -xWKM'
else
#   FOPTIM='-O0 -noalign'
    FOPTIM='-O0 -noalign -CA -CB -CU -CV -CS'
    FFLAGS='-mp -132 -r8 -i4 -w95 -W0 -WB'
fi

LIBS='-lPEPCF90'




