#!/bin/bash
#
#  $Header$
#  $Name$
#


FC='/usr/local/mpich/mpich-1.2.1..7b_pgi/bin/mpif77'
CC='/usr/local/mpich/mpich-1.2.1..7b_pgi/bin/mpicc'
DEFINES='-DWORDLENGTH=4'
INCLUDES='-I/usr/local/mpich/mpich-1.2.1..7b_pgi/include/'
CPP='/lib/cpp  -traditional -P'
LINK='/usr/local/mpich/mpich-1.2.1..7b_pgi/bin/mpif77'
LIBS='-L/usr/local/mpich/mpich-1.2.1..7b_pgi/lib/ -lfmpich -lmpich'


if test "x$IEEE" = x ; then
    #  No need for IEEE-754
    FFLAGS='-byteswapio -r8 -Mnodclchk -Mextend'
    FOPTIM='-tp p6 -v -O2 -Munroll -Mvect=cachesize:512000,transform'
else
    #  Try to follow IEEE-754
    FFLAGS='-byteswapio -r8 -Mnodclchk -Mextend'
    FOPTIM='-tp p6 -v -O2 -Munroll -Mvect=cachesize:512000,transform -Kieee'
fi

# netcdf
# LIBS="$LIBS -lnetcdf"

