#!/bin/bash
#
#  $Header$
#

CPP='/lib/cpp  -traditional -P'
DEFINES='-DWORDLENGTH=1'
FC='sxmpif90 -c'
CC='sxc++'
LINK='sxmpif90'
FFLAGS='-Wf "-pvctl noassume loopcnt=5000000" -sx6 -Pstack'
INCLUDES='-I/SX/usr/include'
