#!/bin/bash
#
#  $Header$
#

S64='$(TOOLSDIR)/set64bitConst.sh'
MAKEDEPEND=makedepend
DEFINES='-DWORDLENGTH=4'

AWK='gawk'
MAKE='gmake'
MAKEDEPEND='$(TOOLSDIR)/xmakedepend'
FC='f77'
LN='/usr/bin/ln -s'
CPP='/usr/ccs/lib/cpp -P'
FFLAGS='-stackvar -explicitpar -vpara -e -u -noautopar -xtypemap=real:64,double:64,integer:32 -fsimple=0'
FOPTIM='-dalign -O3 -xarch=v9'
CFLAGS='-dalign -O3 -xarch=v9'
NOOPTFLAGS='-dalign -O0 -xarch=v9'
