#!/bin/bash

# $Header$

#  This is the local options file for the "new" version of genmake 
#
#  EH3 initial version 2003-08

#DISABLE="obcs zonal_filt shap_filt"
DISABLE="obcs zonal_filt shap_filt kpp"

ENABLE="cal exf"

