#!/bin/bash
#
#  $Header$
#

# This buil-option file was tested on the NAS SGI altix (columbia2).

FC=efc
DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -D_BYTESWAPIO -DWORDLENGTH=4'
LN='/bin/ln -s'
CPP='/lib/cpp  -traditional -P'
FFLAGS='-mp -132 -r8 -i4 -w95 -W0 -WB'
FOPTIM='-O3 -align'
LINK='efc'
LIBS='-L/u/menemenl/software/netcdf-3.5.0/lib -L/opt/sgi/mpt/1.9.1.0//lib -lPEPCF90 -lmpi -lnetcdf'

INCLUDES='-I/opt/sgi/mpt/1.9.1.0/include'
INCLUDEDIRS='/opt/sgi/mpt/1.9.1.0/include'
