#!/bin/bash

# $Header$

#  This is the local options file for the "new" version of genmake 
#
#  EH3 initial version 2003-08


DISABLE="aim shap_filt obcs zonal_filt autodiff cost ctrl grdchk"

ENABLE="cal exf sbo seaice gmredi kpp timeave"
